# Generated by Django 4.2.5 on 2023-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
