# Generated by Django 4.2.5 on 2023-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accountStatus1',
            field=models.BooleanField(default=True),
        ),
    ]
