# Generated by Django 4.2.5 on 2023-10-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth_token',
        ),
    ]
