# Generated by Django 4.2.5 on 2023-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_session_active',
            field=models.BooleanField(default=False),
        ),
    ]
