# Generated by Django 4.2.5 on 2023-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser1',
        ),
    ]
